### ISSUE TITLE
🐛 Error TypeError: channel.isTextBased is not a function

### ISSUE THREAD

**Issue by anondev-sudo** [MarcusOtter/discord-needle#428]
### Describe the bug

When I want to close thread 
![image](https://user-images.githubusercontent.com/85408287/236623394-73de3c9e-046b-445e-a289-5462cb1d8496.png)

```Needle, a Discord bot that declutters your server by creating threads
Copyright (C) 2022  Marcus Otterström
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
[12:07:43] DEBUG: Provided token: ***************************
[12:07:43] DEBUG: Preparing to connect to the gateway...
[12:07:43] DEBUG: [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[12:07:43] DEBUG: [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 997
[12:07:43] DEBUG: [WS => Manager] Using the recommended shard count provided by Discord: 1
[12:07:43] DEBUG: [WS => Manager] Spawning shards: 0
[12:07:43] DEBUG: [WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 10
    Encoding   : json
    Compression: none
[12:07:43] DEBUG: [WS => Shard 0] Setting a HELLO timeout for 20s.
[12:07:43] DEBUG: [WS => Shard 0] [CONNECTED] Took 47ms
[12:07:43] DEBUG: [WS => Shard 0] Clearing the HELLO timeout.
[12:07:43] DEBUG: [WS => Shard 0] Setting a heartbeat interval for 41250ms.
[12:07:43] DEBUG: [WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 33281
[12:07:43] DEBUG: [WS => Shard 0] [READY] Session id.
[12:07:43] DEBUG: [WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[12:07:43] DEBUG: [WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[12:07:43] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 36ms.
Ready!
[12:08:24] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:08:24] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:08:43] Created 0 threads in the last 1.00 minute(s).
[12:09:06] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:09:06] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:09:43] Created 0 threads in the last 1.00 minute(s).
[12:09:47] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:09:47] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 16ms.
[12:10:28] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:10:28] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:10:43] Created 0 threads in the last 1.00 minute(s).
[12:11:09] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:11:09] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 16ms.
[12:11:43] Created 0 threads in the last 1.00 minute(s).
[12:11:51] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:11:51] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:12:32] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:12:32] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:12:43] Created 0 threads in the last 1.00 minute(s).
[12:13:13] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:13:13] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 17ms.
[12:13:43] Created 0 threads in the last 1.00 minute(s).
[12:13:54] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:13:54] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
[12:14:36] DEBUG: [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[12:14:36] DEBUG: [WS => Shard 0] Heartbeat acknowledged, latency of 15ms.
/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:46
        if (channel && !channel.isTextBased()) return;
                                ^
TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:46:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14)```

### Steps to reproduce the bug

1. Open thread
2. Use close thread button
3. See error in console

### Expected behavior

Thread should close

**Comment by MarcusOtter** [comment]
@anondev-sudo I believe you need upgrade your Discord.js version, make sure your clone is up to date with the latest version of Needle.

**Comment by anondev-sudo** [comment]
My bad, I forgot to run npm i after pulling files from GitHub
